Name:           ros-kinetic-pr2-teleop-general
Version:        0.6.0
Release:        0%{?dist}
Summary:        ROS pr2_teleop_general package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/pr2_teleop_general
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kinetic-actionlib
Requires:       ros-kinetic-actionlib-msgs
Requires:       ros-kinetic-angles
Requires:       ros-kinetic-geometry-msgs
Requires:       ros-kinetic-moveit-msgs
Requires:       ros-kinetic-polled-camera
Requires:       ros-kinetic-pr2-arm-kinematics
Requires:       ros-kinetic-pr2-common-action-msgs
Requires:       ros-kinetic-pr2-controller-manager
Requires:       ros-kinetic-pr2-controllers-msgs
Requires:       ros-kinetic-pr2-mannequin-mode
Requires:       ros-kinetic-pr2-mechanism-msgs
Requires:       ros-kinetic-pr2-msgs
Requires:       ros-kinetic-pr2-tuck-arms-action
Requires:       ros-kinetic-ps3joy
Requires:       ros-kinetic-roscpp
Requires:       ros-kinetic-sensor-msgs
Requires:       ros-kinetic-tf
Requires:       ros-kinetic-urdf
BuildRequires:  ros-kinetic-actionlib
BuildRequires:  ros-kinetic-actionlib-msgs
BuildRequires:  ros-kinetic-angles
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-geometry-msgs
BuildRequires:  ros-kinetic-moveit-msgs
BuildRequires:  ros-kinetic-polled-camera
BuildRequires:  ros-kinetic-pr2-common-action-msgs
BuildRequires:  ros-kinetic-pr2-controller-manager
BuildRequires:  ros-kinetic-pr2-controllers-msgs
BuildRequires:  ros-kinetic-pr2-mechanism-msgs
BuildRequires:  ros-kinetic-pr2-msgs
BuildRequires:  ros-kinetic-ps3joy
BuildRequires:  ros-kinetic-roscpp
BuildRequires:  ros-kinetic-sensor-msgs
BuildRequires:  ros-kinetic-tf
BuildRequires:  ros-kinetic-urdf

%description
pr2_teleop_general

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Thu Feb 15 2018 ROS Orphaned Package Maintainers <ros-orphaned-packages@googlegroups.com> - 0.6.0-0
- Autogenerated by Bloom

